### ISSUE TITLE
Doesn't work for IE

### ISSUE THREAD

**Issue by alexmarh** [DWand/nw-fileDialog#2]
IE fails when calling event of non existent in DOM element

I temporarily added input element to the DOM. This fixed the issue:

document.body.appendChild(dialog);
        $timeout(function () {
            dialog.click();
        });
document.body.removeChild(dialog);

**Comment by DWand** [comment]
Hi, @alexmarh. This module is supposed to work only with node-webkit (which is now renamed to [nw.js](https://github.com/nwjs/nw.js/)) browser. To be honest, I'm surprised that you've managed to make it work in IE. As I know, nw.js introduces some tweaks to the standard security policy of browsers, which makes it possible to open both "Open" and "Save as" dialog.
